#!/bin/bash

# Network creation
docker network rm is-net
docker network create is-net

# PostgreSQL creation
docker stop is-postgresql
docker rm is-postgresql
docker run --name is-postgresql --network is-net -e POSTGRES_PASSWORD=topsecret -d postgres

# PSQL connection
docker run -it --rm --network is-net postgres psql -h is-postgresql -U postgres